### ISSUE TITLE
The binaries are non functional, also failed after compiling from source.

### ISSUE THREAD

**Issue by gitgiggity** [wieslawsoltes/ThemeEditor#5]
Like the title says: [Exception Info.txt](https://github.com/wieslawsoltes/ThemeEditor/files/3637815/Exception.Info.txt)

**Comment by basbros** [comment]
Same issue for me. I think the problem is [2194](https://github.com/AvaloniaUI/Avalonia/issues/2194) and [2939](https://github.com/AvaloniaUI/Avalonia/issues/2939).
It compiles if you remove the set of font from style of TextBox.export in the App.xaml (line 108)
` <Setter Property="FontFamily" Value="Consolas"/>`

**Comment by gitgiggity** [comment]
Version 0.8.0 was the last functioning release.
I'll play around with that one, until @wieslawsoltes does quality control prior to publishing.

**Comment by wieslawsoltes** [comment]
@gitgiggity @basbros I have released hotfix release 0.8.2.1 https://github.com/wieslawsoltes/ThemeEditor/releases/tag/0.8.2.1 with this issue fixed.

**Comment by gitgiggity** [comment]
Great
